spring:
  application:
    name: mini-k8s
  datasource:
    url: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/db_users
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  config:
    import: "file:/vault/secrets/db-creds.properties"
  jpa:
    hibernate:
      ddl-auto: update # A changer pour 'validate' ou 'none' en production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
